name: Deploy to Main

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Optional commit message (max 250 chars)'
        required: false
        type: string

jobs:
  call_reusable_deploy:
    uses: ./.github/workflows/reusable-deploy.yml@main
    with:
      source_branch: 'dev'
      dirs_to_rename: 'Sample, Documentation, Assets'
      commit_message: ${{ github.event.inputs.commit_message }}
    secrets: inherit
